### ISSUE TITLE
Fails to follow configuration's quality settings

### ISSUE THREAD

**Issue by mattreecebentley** [jaylinski/kodi-addon-vimeo#14]
When settings are set to 720p, addon will still play at whatever the highest resolution the video is available in. 
Even if the inputstream addon is also set to 720p, vimeo addon will still play at 4k if video is available at 4k.

**Comment by jaylinski** [comment]
@mattreecebentley This is only true for videos with AV1 format and a temporary workaround: https://github.com/jaylinski/kodi-addon-vimeo/blob/v5.0.1/resources/lib/vimeo/api.py#L173

The problem: for some videos (mostly staff pics) Vimeo only returns video-URLs encoded in AV1 format. Since Kodi can't play AV1 yet, the workaround is to use the HLS stream (since it contains mpeg encoded streams).

More detailed post about AV1: https://forum.kodi.tv/showthread.php?tid=220437&pid=2879012#pid2879012

Thread on Kodi AV1 support is here: https://forum.kodi.tv/showthread.php?tid=346272

I could try and filter out non-matching resolutions in the HLS master playlist to make this work. :thinking:

**Comment by jaylinski** [comment]
This should be resolved now with version 5.1.0.
