### ISSUE TITLE
How to call the Vimeo add-on from another add-on

### ISSUE THREAD

**Issue by dagwieers** [jaylinski/kodi-addon-vimeo#38]
I am interested to call a channel from another add-on. We already do this for YouTube where our VOD channels are enhanced by linking to the broadcaster's YouTube content. We now have the same need for Vimeo content from one specific broadcaster.

Is there any documentation on how to call the Vimeo add-on from another add-on to perform certain tasks?

In our own add-on we documented this in the Wiki like [this](https://github.com/add-ons/plugin.video.vrt.nu/wiki/Automation).

**Comment by jaylinski** [comment]
The public API is documented here: https://github.com/jaylinski/kodi-addon-vimeo#api   
There is only one endpoint right now.

You could use the internal API to show a channel:
* `plugin://plugin.video.vimeo/?action=call&call=/channels/927/videos`

This is how it is used internally:
* https://github.com/jaylinski/kodi-addon-vimeo/blob/v5.1.4/resources/lib/models/channel.py#L21-L24

I can also add a public endpoint for this. But it will take a few weeks because I'm currently short on time.

**Comment by dagwieers** [comment]
Not sure how I missed this ;-)

A public endpoint (Do you mean a Script?) is not really needed.

Thanks !

**Comment by jaylinski** [comment]
The "internal" API endpoints can change any time. The "public" endpoints won't change in between major versions.

**Comment by dagwieers** [comment]
Have you considered using routing?

**Comment by jaylinski** [comment]
What exactly are you referring to with "routing"?

**Comment by dagwieers** [comment]
script.module.routing

**Comment by jaylinski** [comment]
Ah, yes, I considered using a routing script. But if I remember right, there were some issues with Python 3 compatibility. I guess that was another routing-script, since the one you linked is up-to-date.

I'll add this to my backlog. :+1:
